config/routes.rb
Rails.application.routes.draw do

	root 'static_pages#home'

	resources :users, only: [:new, :create, :show]
	post '/users/new', to: 'users#create'
	resources :sessions, only: [:new, :create, :destroy]
  	get '/signin', to: 'sessions#new'
  	post '/sessions/new', to: 'sessions#create'
  	get '/signout', to: 'sessions#destroy'
  	delete '/signout', to: 'sessions#destroy'
  	post '/events/new', to: 'events#create'
  	resources :events, only: [:new, :create, :show, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :attendee, :class_name => "User"
	belongs_to :attended_event, :class_name => "Event"
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :creater, :class_name => "User"
	has_many :attendance, foreign_key: :attended_event_id
	has_many :attendees, :through => :attendance, :source => :attendee
	scope :past_events, -> { where("date < ?", Time.zone.now) }
	scope :upcoming_events, -> { where("date > ?", Time.zone.now) }


# 	Commented out because scope is being used instead.
#	def self.past_events
#		self.all.select { |event| event.date.to_i < Time.zone.now.to_i}
#	end

#	def self.upcoming_events
#		self.all.select { |event| event.date.to_i > Time.zone.now.to_i}
#	end
end

app/models/user.rb
class User < ApplicationRecord
	before_create :create_remember_token
	has_many :created_events, foreign_key: :creater_id, class_name: "Event"
	has_many :attendance, foreign_key: :attendee_id
	has_many :attended_events, :through => :attendance, :source => :attended_event

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	def upcoming_events
		self.attended_events.select { |event| event.date.to_i > Time.zone.now.to_i}
	end

	def previous_events
		self.attended_events.select { |event| event.date.to_i < Time.zone.now.to_i}
	end

	private

		def create_remember_token
			self.remember_token = User.digest(User.new_remember_token)
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	protect_from_forgery with: :exception

  	include SessionsHelper


end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def new
	end

	def create
		@user = current_user
		@event = @user.created_events.build(event_params)
		@event.save
		@event.attendance.create(attendee_id: @user.id)
		redirect_to @user
	end

	def show
		@event = Event.find_by(id: params[:id])
	end

	def index
		@events = Event.all
		@past_events = Event.past_events
		@upcoming_events = Event.upcoming_events
	end

	private

		def event_params
			params.require(:event).permit(:name, :date, :place, :description)
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		@user = User.find_by(name: params[:session][:name])
		if @user
			sign_in @user
			redirect_to @user
		else
			render 'new'
		end
	end 

	def destroy
		sign_out
		redirect_to root_path
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			puts "heading to sign_in"
			sign_in(@user)
			puts "heading to redirect_to"
			redirect_to @user
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
		@upcoming_events = @user.upcoming_events
		@previous_events = @user.previous_events
	end

	private

		def user_params
			params.require(:user).permit(:name)
		end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
  		remember_token = User.new_remember_token
  		cookies.permanent[:remember_token] = remember_token
  		user.update_attribute(:remember_token, User.digest(remember_token))
  		self.current_user = user
  	end

  	def current_user
  		remember_token = User.digest(cookies[:remember_token])
  		@current_user ||= User.find_by(remember_token: remember_token)
  	end

  	def current_user=(user)
  		@current_user = user
  	end

  	def sign_out
  		current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
  		cookies[:remember_token] = nil
  	end

  	def signed_in_user
  		unless signed_in?
  			redirect_to signin_url
  		end
  	end

  	def signed_in?
  		!current_user.nil?
  	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>All Events</h1>

<h3>Upcoming events</h3>
<table>
	<% @upcoming_events.each do |event| %>
		<tr>
			<td><strong><%= link_to "#{event.name}", event %></strong></td>
			<td> - Created by: <%= link_to "#{event.creater.name}", event.creater %></td>
			<td> - <%= event.place %></td>
			<td> - <%= event.date.strftime("%B %d, %Y") %></td>
		</tr>
	<% end %>
</table>

<h3>Past events</h3>
<table>
	<% @past_events.each do |event| %>
		<tr>
			<td><strong><%= link_to "#{event.name}", event %></strong></td>
			<td> - Created by: <%= link_to "#{event.creater.name}", event.creater %></td>
			<td> - <%= event.place %></td>
			<td> - <%= event.date.strftime("%B %d, %Y") %></td>
		</tr>
	<% end %>
</table>

app/views/events/new.html.erb
<h1>Create an event</h1>
<%= form_for(:event) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :date %>
	<%= f.date_field :date %>

	<%= f.label :place %>
	<%= f.text_field :place %><br>

	<%= f.label :description %><br>
	<%= f.text_area :description %><br>

	<%= f.submit "Create event" %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<ul>
	<li>Posted by: <%= link_to "#{@event.creater.name}", @event.creater %></li>
	<li><%= @event.place %></li>
	<li><%= @event.date.strftime("%B %d, %Y") %></li>
	<li><%= @event.description %></li>
</ul>

<h3>Attendees:</h3>
<ul>
	<% @event.attendees.each do |attendee| %>
		<li><%= link_to "#{attendee.name}", attendee %></li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvent</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if signed_in? %>
  		<p>Currently signed in as <%= link_to "#{current_user.name}", current_user %>. <%= link_to "Create an event", new_event_path %> <%= link_to "Events", events_path %>    <%= link_to "Sign out", signout_path %></p>
  	<% else %>
  		<p><%= link_to "Sign in", signin_path %>    <%= link_to "Create an account", new_user_path %></p>
  	<% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>This is the Home Page</h1>

app/views/users/new.html.erb
<h1>Create an account</h1>

<div>
	<%= form_for(:user) do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.submit "Create user" %>
	<% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<h3>Created events: </h3>
<ul class="created_events">
	<% @user.created_events.each do |event| %>
		<li><%= link_to "#{event.name}", event %>
			<ul>
				<li><%= event.place %></li>
				<li><%= event.date.strftime("%B %d, %Y") %></li>
			</ul>
		</li>
	<% end %>
</ul>

<h3>Upcoming events:</h3>
<ul class="attended_events">
	<% @upcoming_events.each do |event| %>
		<li><%= link_to "#{event.name}", event %>
			<ul>
				<li><%= event.place %></li>
				<li><%= event.date.strftime("%B %d, %Y") %></li>
			</ul>
		</li>
	<% end %>
</ul>

<h3>Previous events:</h3>
<ul class="attended_events">
	<% @previous_events.each do |event| %>
		<li><%= link_to "#{event.name}", event %>
			<ul>
				<li><%= event.place %></li>
				<li><%= event.date.strftime("%B %d, %Y") %></li>
			</ul>
		</li>
	<% end %>
</ul>